name: dev-${GITHUB_PR}
services: 
  dev-ip: 
    profiles: [ip, all]
    container_name: dev-${GITHUB_PR}-ip
    user: 1000:1000
    build: .
    restart: always 
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ip-${GITHUB_PR}.rule=Host(`dev-${GITHUB_PR}.institutionpenguin.com`)"
      - "traefik.http.routers.ip-${GITHUB_PR}.entrypoints=web"
      - "traefik.http.services.ip-${GITHUB_PR}.loadbalancer.server.port=3000"
    networks: 
      - traefik 
      - default
  dev-ip-db: 
    profiles: [db, all]
    container_name: dev-${GITHUB_PR}-ip-db
    user: 1000:1000
    image: mongo:latest 
    restart: always
    env_file:
      - .env
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js 
      
networks: 
  default: 
  traefik: 
    external: true 
    name: traefik