services: 
  ip: 
    profiles: [ip, all]
    container_name: dev-${GITHUB_BRANCH}-ip
    build: .
    restart: always 
    env_file:
      - .env
    networks:
      - default 
      - proxy
  ip-db: 
    profiles: [db, all]
    container_name: dev-${GITHUB_BRANCH}-ip-db
    image: mongo:latest 
    restart: always
    env_file:
      - .env
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js 
      
networks: 
  default:
  proxy: 
    name: proxy
    external: true