services: 
  ip: 
    profiles: [ip, all]
    build: .
    container_name: ip 
    restart: always 
    env_file:
      - .env
    networks:
      - default 
      - proxy
  mongodb: 
    profiles: [db, all]
    image: mongo:latest 
    container_name: ip-db 
    restart: always
    env_file:
      - .env
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js 
    # Open for testing
    ports: 
      - "127.0.0.1:27017:27017"
networks: 
  default:
  proxy: 
    name: proxy
    external: true