# Autocreate PR when a new branch is created
name: Autocreate PR
on: 
  push: 
    branches: 
      - '*'

jobs: 
  create-pull-request: 
    runs-on: self-hosted

    # Not for dependabot automerges
    if: ${{ github.event.pusher.username != 'dependabot[bot]' }}

    steps:
      
        # Workaround
      - name: Clean up GitHub workspace
        uses: docker://ubuntu:latest
        with:
          args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +
  
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatic Pull Request
          commit-message: Automated pull request created
          body: |
            This pull request was automatically created when a new branch was created.