name: Build docker container
on:
  pull_request:
jobs:
  build-deploy:
    runs-on: self-hosted
    container: 
      image: ubuntu:latest
    steps:
      - name: Reset Permission
        uses: AutoModality/action-clean@v1
      - name: Check out code
        uses: actions/checkout@v4
        with: 
          path: '${{ github.ref }}'
      - name: Build docker
        env:
          AUTH_ID: ${{ secrets.AUTH_ID }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: docker compose build