# Builds the container and runs cypress tests 
name: Build docker container
on:
  pull_request:
jobs:
  run-tests: 

    # Runs on d3 runner
    runs-on: self-hosted 
    environment: Dev

    steps: 
      - name: Check out code 
        uses: actions/checkout@v4

      - name: Build docker containers
        run: |
          docker compose --profile db up
          docker compose --profile ip up 

      # Execute cypress tests
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn start
          wait-on: "http://localhost:3000"
        
      - name: Stop docker containers 
        run: docker compose --profile all down 
