# Builds the container and runs cypress tests 
name: Build docker container
on:
  pull_request:
jobs:
  run-tests: 
    runs-on: self-hosted 
    container:
        image: cypress/browsers
    steps:        
      - name: Cache Cypress 
        id: cache-cypress   
        uses: actions/cache@v4
        with: 
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Check out code 
        uses: actions/checkout@v4 
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"