# Builds the container and runs cypress tests 
name: Build docker container
on:
  pull_request:
jobs:
  run-tests: 
    runs-on: self-hosted 
    environment: Dev
    container:
        image: cypress/browsers
    steps:        
      - name: Check out code 
        uses: actions/checkout@v4 
      # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching
      - name: Cache NPM
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"