# Builds the container and runs cypress tests 
name: Build docker container
on:
  pull_request:
jobs:
  run-tests: 

    # Runs on d3 runner
    runs-on: self-hosted 
    environment: Dev

    steps: 
      - name: Check out code 
        uses: actions/checkout@v4
        
      - name: Set environmental variables
        run: |
          echo "AUTH_ID=${{ secrets.AUTH_ID }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "IP_URL=${{ secrets.IP_URL }}" >> .env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "MONGODB_DB=${{ secrets.MONGODB_DB }}" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "GITHUB_BRANCH"=${{ github.ref_slug }}
          
      - name: Build docker containers
        run: |
          docker compose --profile db up -d
          docker compose --profile ip up -d

      # Execute cypress tests
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn start
          wait-on: "http://localhost:3000"
        
      - name: Stop docker containers 
        run: docker compose --profile all down 

      - name: Remove .env 
        run: rm .env
