# Builds the container and runs cypress tests 
name: Build docker container
on:
  pull_request:
jobs:
  run-tests: 
    runs-on: self-hosted 
    environment: Dev
    container:
        image: cypress/browsers
    steps:        
      - name: Check out code 
        uses: actions/checkout@v4 
      - name: Cache Next Build
        uses: actions/cache@v3
        with:
          path: |
            ./.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('*.js', '*.jsx', '*.ts', '*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"