name: Update docker container
on:
  push: 
    branches: 
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    environment: Prod
    steps:
      - name: Clean up GitHub workspace
        uses: docker://ubuntu:latest
        with:
          args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker
        env:
          AUTH_ID: ${{ secrets.AUTH_ID }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }} 
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }} 
        run: docker compose build
      - name: Deploy docker
        run: docker compose up -d
