# Deploys main merges to prod
name: Update docker container
on:
  push: 
    branches: 
      - main
jobs:
  build-deploy:

    # Runs on d3 runner
    runs-on: self-hosted
    environment: Prod
    steps:

      # Storage cleanup workaround
      - name: Clean up GitHub workspace
        uses: docker://ubuntu:latest
        with:
          args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set environmental variables
        run: |
          echo "AUTH_ID=${{ secrets.AUTH_ID }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
      - name: Build docker
        run: docker compose build
      - name: Deploy docker
        run: docker compose up -d

      # Second storage cleanup workaround
      - name: Clean-up docker
        run: docker system prune -f
