name: Run cypress tests on push
on:
  push:
jobs:
  run-tests: 
    runs-on: self-hosted 
    container:
        image: node:latest
    steps: 
      - name: Check out code 
        uses: actions/checkout@v4 
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6