name: Run cypress tests on push
on:
  push:
    branches:
    - 'main'
jobs:
  run-tests: 
    runs-on: self-hosted 
    container:
        image: cypress/browsers
    steps: 
      - name: Check out code 
        uses: actions/checkout@v4 
      - name: Run cypress tests 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
