name: Update docker container on main
on:
  push: 
    branches: 
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Import ENV
      env:
        AUTH_ID: ${{ secrets.AUTH_ID }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker
        run: docker compose build
      - name: Deploy docker
        run: docker compose up -d