name: Update docker container on main
on:
  push: 
    branches: 
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker
        run: docker compose build
      - name: Deploy docker
        run: docker compose up -d