name: Update docker container
on:
  push: 
    branches: 
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    environment: Prod
    steps:
      - name: Reset Permission
        uses: AutoModality/action-clean@v1
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker
        env:
          AUTH_ID: ${{ secrets.AUTH_ID }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: docker compose build
      - name: Deploy docker
        run: docker compose up -d
